name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - "master"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  pytest:
    name: PY Test
    runs-on: ubuntu-20.04

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Lightning
        run: |
          python -m pip install -r requirements.txt -r tests/requirements.txt --quiet --extra-index-url https://tinyurl.com/n2scv9p4
          python -m pip install . --quiet

      - name: Tests
        run: |
          pytest tests
